// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240822145824_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api.Models.Basvuru", b =>
                {
                    b.Property<int>("BasvuruId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BasvuruId"));

                    b.Property<DateTime>("AciklamaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BasvuranBirimId")
                        .HasColumnType("INT");

                    b.Property<int>("BasvuruDonemiId")
                        .HasColumnType("INT");

                    b.Property<int>("BasvuruDurumuId")
                        .HasColumnType("INT");

                    b.Property<DateTime>("BasvuruTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BasvuruYapilanProjeId")
                        .HasColumnType("INT");

                    b.Property<int>("BasvuruYapilanTurId")
                        .HasColumnType("INT");

                    b.Property<decimal>("HibeTutari")
                        .HasColumnType("numeric");

                    b.Property<int>("KatilimciTuruId")
                        .HasColumnType("INT");

                    b.Property<string>("ProjeAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BasvuruId");

                    b.HasIndex("BasvuranBirimId");

                    b.HasIndex("BasvuruDonemiId");

                    b.HasIndex("BasvuruDurumuId");

                    b.HasIndex("BasvuruYapilanProjeId");

                    b.HasIndex("BasvuruYapilanTurId");

                    b.HasIndex("KatilimciTuruId");

                    b.ToTable("Basvuru");
                });

            modelBuilder.Entity("api.Models.BasvuruKullanici", b =>
                {
                    b.Property<int>("BasvuruKullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BasvuruKullaniciId"));

                    b.Property<int>("BasvuruId")
                        .HasColumnType("integer");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.HasKey("BasvuruKullaniciId");

                    b.HasIndex("BasvuruId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("BasvuruKullanici");
                });

            modelBuilder.Entity("api.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KullaniciId"));

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SilinmeDurumu")
                        .HasColumnType("boolean");

                    b.HasKey("KullaniciId");

                    b.ToTable("Kullanici");
                });

            modelBuilder.Entity("api.Models.Tipler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AltTip")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<bool?>("SilinmeDurumu")
                        .HasColumnType("boolean");

                    b.Property<string>("Tip")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<int?>("TipKod")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.ToTable("Tipler");
                });

            modelBuilder.Entity("api.Models.Basvuru", b =>
                {
                    b.HasOne("api.Models.Tipler", "BasvuranBirim")
                        .WithMany()
                        .HasForeignKey("BasvuranBirimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Tipler", "BasvuruDonemi")
                        .WithMany()
                        .HasForeignKey("BasvuruDonemiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Tipler", "BasvuruDurumu")
                        .WithMany()
                        .HasForeignKey("BasvuruDurumuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Tipler", "BasvuruYapilanProje")
                        .WithMany()
                        .HasForeignKey("BasvuruYapilanProjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Tipler", "BasvuruYapilanTur")
                        .WithMany()
                        .HasForeignKey("BasvuruYapilanTurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Tipler", "KatilimciTuru")
                        .WithMany()
                        .HasForeignKey("KatilimciTuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BasvuranBirim");

                    b.Navigation("BasvuruDonemi");

                    b.Navigation("BasvuruDurumu");

                    b.Navigation("BasvuruYapilanProje");

                    b.Navigation("BasvuruYapilanTur");

                    b.Navigation("KatilimciTuru");
                });

            modelBuilder.Entity("api.Models.BasvuruKullanici", b =>
                {
                    b.HasOne("api.Models.Basvuru", "Basvuru")
                        .WithMany()
                        .HasForeignKey("BasvuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basvuru");

                    b.Navigation("Kullanici");
                });
#pragma warning restore 612, 618
        }
    }
}
